# Generated by Django 3.1.6 on 2021-02-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freecourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('coursename', models.TextField(max_length=500)),
                ('link', models.TextField(max_length=200)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('titledescription', models.TextField(max_length=200)),
                ('about', models.TextField(max_length=100)),
                ('aboutjob', models.TextField(max_length=500)),
                ('hiringdetails', models.TextField(max_length=500)),
                ('Eligibility', models.TextField(max_length=1000)),
                ('applylink', models.TextField(max_length=100)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Udemycourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics')),
                ('coursetitle', models.TextField(max_length=500)),
                ('link', models.TextField(max_length=200)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
